src/hflan/PartnersBundle/Entity/Partner.php
<?php

namespace hflan\PartnersBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Partner
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="hflan\PartnersBundle\Entity\PartnerRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Partner
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", unique=true, length=127)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="sort_index", type="integer")
     */
    private $sort_index;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Url()
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=255)
     */
    private $path;

    /**
     * @Assert\Image(maxSize = "1M")
     */
    private $file;

    public function __construct()
    {
        $this->sort_index = 1;
    }

    public function getAbsolutePath()
    {
        return null === $this->path ? null : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return null === $this->path ? null : $this->getUploadDir().'/'.$this->path;
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads';
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Partner
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Partner
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set sort_index
     *
     * @param integer $sortIndex
     * @return Partner
     */
    public function setSortIndex($sortIndex)
    {
        $this->sort_index = $sortIndex;
    
        return $this;
    }

    /**
     * Get sort_index
     *
     * @return integer 
     */
    public function getSortIndex()
    {
        return $this->sort_index;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Partner
     */
    public function setUrl($url)
    {
        $this->url = $url;
    
        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Partner
     */
    public function setPath($path)
    {
        $this->path = $path;
    
        return $this;
    }

    /**
     * Get path
     *
     * @return string 
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->file) {
            if ($file = $this->getAbsolutePath()) {
                if(is_file($file))
                    unlink($file);
            }
            $this->path = sha1(uniqid(mt_rand(), true)).'.'.$this->file->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->file) {
            return;
        }

        $this->file->move($this->getUploadRootDir(), $this->path);

        unset($this->file);
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;
    }
}

src/hflan/PartnersBundle/Form/PartnerType.php
<?php

namespace hflan\PartnersBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PartnerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array('label' => 'partners.field.name'))
            ->add('description', 'textarea', array('label' => 'partners.field.description'))
            ->add('url', 'text', array('label' => 'partners.field.url'))
            ->add('sort_index', null, array('label' => 'partners.field.priority'))
            ->add('file', 'file', array('label' => 'partners.field.logo', 'required' => false))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'hflan\PartnersBundle\Entity\Partner'
        ));
    }

    public function getName()
    {
        return 'hflan_partnersbundle_partnertype';
    }
}

src/hflan/PartnersBundle/Controller/PartnersController.php
<?php

namespace hflan\PartnersBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use JMS\SecurityExtraBundle\Annotation\Secure;
use hflan\PartnersBundle\Entity\Partner;
use hflan\PartnersBundle\Form\PartnerType;

class PartnersController extends Controller
{
    public function indexAction()
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanPartnersBundle:Partner');

        $partners = $repository->findBy(array(), array('sort_index'=>'ASC'));

        return $this->render('hflanPartnersBundle:Partners:index.html.twig', array(
            'partners' => $partners
        ));
    }

    /**
     * @Secure(roles="ROLE_COM")
     */
    public function newAction()
    {
        $partner = new Partner;

        $form = $this->createForm(new PartnerType, $partner);

        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if( $form->isValid() )
            {
                $em = $this->getDoctrine()->getManager();
                $em->persist($partner);
                $em->flush();

                $this->get('session')->setFlash('success', "partners.message.success.new");
                return $this->redirect( $this->generateUrl('hflan_partners_index') );
            }
        }

        return $this->render('hflanPartnersBundle:Partners:new.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Secure(roles="ROLE_COM")
     */
    public function adminAction()
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanPartnersBundle:Partner');

        $partners = $repository->findBy(array(), array('sort_index'=>'ASC'));

        $form = $this->createFormBuilder(array())
            ->add('batch_action', 'choice', array(
            'choices' => array(
                'delete' => $this->get('translator')->trans('partners.action.delete')),
            'label' => 'partners.action.selection'));

        foreach($partners as $partner)
            $form->add(''.$partner->getId(), 'checkbox', array('required' => false));

        $form = $form->getForm();

        $request = $this->get('request');
        if ($request->getMethod() == 'POST')
        {
            $form->bind($request);
            $data = $form->getData();
            $em = $this->getDoctrine()->getManager();

            foreach($partners as $partner)
            {
                if($data[$partner->getId()] == 1)
                {
                    if($data['batch_action'] == 'delete')
                        $em->remove($partner);
                }
            }

            $em->flush();
            $messages = array(
                'delete' => "partners.message.success.delete"
            );
            $this->get('session')->setFlash('success', $messages[ $data['batch_action'] ]);
            return $this->redirect( $this->generateUrl('hflan_partners_admin') );
        }

        return $this->render('hflanPartnersBundle:Partners:admin.html.twig', array(
            'partners' => $partners,
            'form' => $form->createView(),
        ));
    }

    /**
     * @Secure(roles="ROLE_COM")
     */
    public function editAction(Partner $partner)
    {
        $form = $this->createForm(new PartnerType(), $partner);

        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if( $form->isValid() )
            {
                $partner->preUpload();
                $em = $this->getDoctrine()->getManager();
                $em->persist($partner);
                $em->flush();

                $this->get('session')->setFlash('success', 'partners.message.success.update');
                return $this->redirect( $this->generateUrl('hflan_partners_index') );
            }
            else
                $this->get('session')->setFlash('error', "message.error.form");
        }
        return $this->render('hflanPartnersBundle:Partners:edit.html.twig', array(
            'form' => $form->createView(),
            'partner' => $partner
        ));
    }

    public function menuAction()
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanPartnersBundle:Partner');

        $partners = $repository->findBy(array(), array('sort_index'=>'ASC'));

        return $this->render('hflanPartnersBundle:Partners:menu.html.twig', array(
            'partners' => $partners
        ));
    }
}

src/hflan/PartnersBundle/Resources/views/Partners/admin.html.twig
{% extends "hflanPartnersBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}partners.title.page.admin{% endtrans %}
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}partners.title.page.admin{% endtrans %}</small>
{% endblock%}

{% block administration %}
<h2>{% trans %}partners.title.aside.admin{% endtrans %}</h2>
<a href="{{ path('hflan_partners_new') }}" class="btn"><i class="icon-plus icon-white"></i> {% trans %}partners.action.new{% endtrans %}</a>
<hr>
{% endblock %}

{% block partners %}

{% if partners is empty %}
<p>{% trans %}partners.message.create_new{% endtrans %}</p>
{% else %}

<form method="post" {{ form_enctype(form) }}>
    <table class="table">
        <tr>
            <th>{% trans %}partners.field.name{% endtrans %}</th>
            <th>{% trans %}partners.field.url{% endtrans %}</th>
        </tr>
        {% for partner in partners %}
        <tr href="{{ path('hflan_partners_edit', {id: partner.id}) }}" class="selectable">
            <td>{{ form_widget(form[partner.id]) }} {{ partner.name }}</td>
            <td>{{ partner.url }}</td>
        </tr>
        {% endfor %}
    </table>
    <div class="form-action" style="margin-top: 5px;">
        {{ form_label(form.batch_action) }}
        {{ form_widget(form.batch_action) }}
        {{ form_rest(form) }}
        <button type="submit" class="btn">Go</button>
    </div>
</form>

{% endif %}

{% endblock %}

src/hflan/PartnersBundle/Resources/views/Partners/edit.html.twig
{% extends "hflanPartnersBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}partners.title.page.edit{% endtrans %}
{% endblock %}

{% block administration %}
<h2>{% trans %}partners.title.aside.admin{% endtrans %}</h2>
<a href="{{ path('hflan_partners_admin') }}" class="btn"><i class="icon-th-list icon-white"></i> {% trans %}partners.action.list{% endtrans %}</a>
<hr>
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}partners.title.page.edit{% endtrans %}</small>
{% endblock %}

{% block partners %}

<form method="post" {{ form_enctype(form) }} class="form">
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.url) }}
    {{ form_row(form.sort_index) }}
    {{ form_row(form.file) }}
    {% if partner.path is not empty %}
    <div class="form-widget">
        <img src="{{ asset(partner.webPath)}}" alt="preview" class="preview-img">
    </div>
    {% endif %}
    {{ form_rest(form) }}
    <div class="form-action">
        <input type="submit" class="btn" value="{% trans %}partners.action.save{% endtrans %}" />
    </div>
</form>

{% endblock %}

src/hflan/PartnersBundle/Resources/views/Partners/index.html.twig
{% extends "hflanPartnersBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}partners.title.page.index{% endtrans %}
{% endblock %}

{% block administration %}
    {% if is_granted('ROLE_COM') %}
        <h2>{% trans %}partners.title.aside.admin{% endtrans %}</h2>
        <a href="{{ path('hflan_partners_new') }}" class="btn"><i class="icon-plus icon-white"></i> {% trans %}partners.action.new{% endtrans %}</a>
        <a href="{{ path('hflan_partners_admin') }}" class="btn"><i class="icon-th-list icon-white"></i> {% trans %}partners.action.list{% endtrans %}</a>
        <hr>
    {% endif %}
{% endblock %}

{% block partners %}

<div class="partners-list">
{% for partner in partners %}
    <a href="{{ partner.url }}">
       <img src="{{ asset(partner.webPath) }}" alt="{{ partner.name }}" title="{{ partner.description }}">
    </a>
{% endfor %}
</div>

{% endblock %}

src/hflan/PartnersBundle/Resources/views/Partners/menu.html.twig
<h2>{% trans %}partners.title.aside.show{% endtrans %}</h2>
<p>{% trans %}partners.message.invite{% endtrans %}</p>
<div class="partner-menu">
    {% for partner in partners %}
    <a href="{{ partner.url }}">
        <img src="{{ asset(partner.webPath) }}" alt="{{ partner.name}}" title="{{ partner.description}}">
    </a>
    {% endfor %}
</div>
<div style="clear: both"></div>
<hr>

src/hflan/PartnersBundle/Resources/views/Partners/new.html.twig
{% extends "hflanPartnersBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}partners.title.page.new{% endtrans %}
{% endblock %}

{% block administration %}
<h2>{% trans %}partners.title.aside.admin{% endtrans %}</h2>
<a href="{{ path('hflan_partners_admin') }}" class="btn"><i class="icon-th-list icon-white"></i> {% trans %}partners.action.list{% endtrans %}</a>
<hr>
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}partners.title.page.new{% endtrans %}</small>
{% endblock %}

{% block partners %}

<form method="post" {{ form_enctype(form) }} class="form">
    {{ form_widget(form) }}
    <div class="form-action">
        <input type="submit" class="btn" value="{% trans %}partners.action.save{% endtrans %}" />
    </div>
</form>

{% endblock %}