src/hflan/TournamentBundle/Entity/Tournament.php
<?php

namespace hflan\TournamentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * tournament
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="hflan\TournamentBundle\Entity\TournamentRepository")
 */
class Tournament
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=127)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="game", type="string", length=127)
     * @Assert\NotBlank()
     */
    private $game;

    /**
     * @var integer
     *
     * @ORM\Column(name="nbrTeams", type="integer")
     * @Assert\NotBlank()
     */
    private $nbrTeams;

    /**
     * @var integer
     *
     * @ORM\Column(name="playersPerTeam", type="integer")
     * @Assert\NotBlank()
     */
    private $playersPerTeam;

    /**
     * @var integer
     *
     * @ORM\Column(name="price", type="integer")
     * @Assert\NotBlank()
     */
    private $price;

    /**
     * @var string
     *
     * @ORM\Column(name="embedded_player", type="text", nullable=true)
     */
    private $embeddedPlayer;

    /**
     * @var boolean
     *
     * @ORM\Column(name="casu", type="boolean")
     */
    private $casu;

    /**
     * @ORM\ManyToOne(targetEntity="hflan\TournamentBundle\Entity\Event", inversedBy="tournaments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event;

    /**
     * @ORM\OneToMany(targetEntity="hflan\TournamentBundle\Entity\Team", mappedBy="tournament", cascade={"remove"})
     */
    protected $teams;

    /**
     * @ORM\OneToMany(targetEntity="hflan\TournamentBundle\Entity\CustomField", mappedBy="tournament", cascade={"persist", "remove"})
     */
    protected $customFields;

    public function __construct($type)
    {
        $this->name = "Tournoi ";
        $this->nbrTeams = 16;
        $this->playersPerTeam = 1;
        $this->teams = new ArrayCollection();
        $this->customFields = new ArrayCollection();
        $this->casu = false;

        if($type == 'casu')
        {
            $this->setName('Freeplay/Visiteur');
            $this->setNbrTeams(40);
            $this->setCasu(true);
            $this->setPlayersPerTeam(1);
            $this->setGame('none');
            $this->setPrice(0);
        }
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getPrizePool()
    {
        return $this->nbrTeams*$this->price*$this->playersPerTeam;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return tournament
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set game
     *
     * @param string $game
     * @return tournament
     */
    public function setGame($game)
    {
        $this->game = $game;
    
        return $this;
    }

    /**
     * Get game
     *
     * @return string 
     */
    public function getGame()
    {
        return $this->game;
    }

    /**
     * Set nbrTeams
     *
     * @param integer $nbrTeams
     * @return tournament
     */
    public function setNbrTeams($nbrTeams)
    {
        $this->nbrTeams = $nbrTeams;
    
        return $this;
    }

    /**
     * Get nbrTeams
     *
     * @return integer 
     */
    public function getNbrTeams()
    {
        return $this->nbrTeams;
    }

    /**
     * Set playersPerTeam
     *
     * @param integer $playersPerTeam
     * @return tournament
     */
    public function setPlayersPerTeam($playersPerTeam)
    {
        $this->playersPerTeam = $playersPerTeam;
    
        return $this;
    }

    /**
     * Get playersPerTeam
     *
     * @return integer 
     */
    public function getPlayersPerTeam()
    {
        return $this->playersPerTeam;
    }

    /**
     * Set price
     *
     * @param integer $price
     * @return tournament
     */
    public function setPrice($price)
    {
        $this->price = $price;
    
        return $this;
    }

    /**
     * Get price
     *
     * @return integer 
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set event
     *
     * @param \hflan\TournamentBundle\Entity\Event $event
     * @return Tournament
     */
    public function setEvent(\hflan\TournamentBundle\Entity\Event $event)
    {
        $this->event = $event;
    
        return $this;
    }

    /**
     * Get event
     *
     * @return \hflan\TournamentBundle\Entity\Event 
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Add teams
     *
     * @param \hflan\TournamentBundle\Entity\Team $teams
     * @return Tournament
     */
    public function addTeam(\hflan\TournamentBundle\Entity\Team $teams)
    {
        $this->teams[] = $teams;
    
        return $this;
    }

    /**
     * Remove teams
     *
     * @param \hflan\TournamentBundle\Entity\Team $teams
     */
    public function removeTeam(\hflan\TournamentBundle\Entity\Team $teams)
    {
        $this->teams->removeElement($teams);
    }

    /**
     * Get teams
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getTeams()
    {
        return $this->teams;
    }

    /**
     * Set casu
     *
     * @param boolean $casu
     * @return Tournament
     */
    public function setCasu($casu)
    {
        $this->casu = $casu;
    
        return $this;
    }

    /**
     * Get casu
     *
     * @return boolean 
     */
    public function getCasu()
    {
        return $this->casu;
    }

    /**
     * Set embeddedPlayer
     *
     * @param string $embeddedPlayer
     * @return Tournament
     */
    public function setEmbeddedPlayer($embeddedPlayer)
    {
        $this->embeddedPlayer = $embeddedPlayer;
    
        return $this;
    }

    /**
     * Get embeddedPlayer
     *
     * @return string 
     */
    public function getEmbeddedPlayer()
    {
        return $this->embeddedPlayer;
    }

    /**
     * Add customFields
     *
     * @param \hflan\TournamentBundle\Entity\CustomField $customFields
     * @return Tournament
     */
    public function addCustomField(\hflan\TournamentBundle\Entity\CustomField $customFields)
    {
        $customFields->setTournament($this);
        $this->customFields[] = $customFields;
    
        return $this;
    }

    /**
     * Remove customFields
     *
     * @param \hflan\TournamentBundle\Entity\CustomField $customFields
     */
    public function removeCustomField(\hflan\TournamentBundle\Entity\CustomField $customFields)
    {
        $this->customFields->removeElement($customFields);
    }

    /**
     * Get customFields
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCustomFields()
    {
        return $this->customFields;
    }
}

src/hflan/TournamentBundle/Form/EventType.php
<?php

namespace hflan\TournamentBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, array('label'=>'tournament.field.name'))
            ->add('price', null, array('label'=>'tournament.field.price', 'attr'=>array('placeholder'=>'€')))
            ->add('start_at', 'datetime', array('label'=>'tournament.field.start_at', 'date_widget'=>'single_text', 'date_format'=>'dd/MM/yyyy'))
            ->add('end_at', 'datetime', array('label'=>'tournament.field.end_at', 'date_widget'=>'single_text', 'date_format'=>'dd/MM/yyyy'))
            ->add('public', null, array('label'=>'tournament.field.public', 'required'=>false))
            ->add('open_at', 'datetime', array('label'=>'tournament.field.open_at', 'date_widget'=>'single_text', 'date_format'=>'dd/MM/yyyy'))
            ->add('close_at', 'datetime', array('label'=>'tournament.field.close_at', 'date_widget'=>'single_text', 'date_format'=>'dd/MM/yyyy'))
            ->add('open', null, array('label'=>'tournament.field.open', 'required'=>false))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'hflan\TournamentBundle\Entity\Event'
        ));
    }

    public function getName()
    {
        return 'hflan_tournamentbundle_eventtype';
    }
}

src/hflan/TournamentBundle/Form/PlayerType.php
<?php

namespace hflan\TournamentBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PlayerType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname', null, array('label'=>'tournament.field.firstname', 'required'=>false))
            ->add('lastname', null, array('label'=>'tournament.field.lastname', 'required'=>false))
            ->add('nickname', null, array('label'=>'tournament.field.nickname', 'required'=>false))
            ->add('email', null, array('label'=>'tournament.field.email', 'required'=>false))
            ->add('birthday', 'date', array('label'=>'tournament.field.birthday', 'required'=>false, 'widget'=>'single_text', 'format'=>'dd/MM/yyyy', 'attr'=>array('placeholder'=>'ex: 31/12/1995')))
            ->add('pc_type', 'choice', array('label'=>'tournament.field.pcType', 'choices'=>array('Descktop'=>'Descktop', 'Laptop'=>'Laptop'), 'attr'=>array('style'=>'width:178px')))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'hflan\TournamentBundle\Entity\Player'
        ));
    }

    public function getName()
    {
        return 'hflan_tournamentbundle_playertype';
    }
}

src/hflan/TournamentBundle/Controller/EventController.php
<?php

namespace hflan\TournamentBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use JMS\SecurityExtraBundle\Annotation\Secure;
use hflan\TournamentBundle\Entity\Event;
use hflan\TournamentBundle\Form\EventType;

class EventController extends Controller
{
    /**
     * @Secure(roles="ROLE_RESPO")
     */
    public function indexAction()
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanTournamentBundle:Event');

        $events = $repository->findBy(array(), array('start_at'=>'ASC'));

        return $this->render('hflanTournamentBundle:Event:index.html.twig', array(
            'events' => $events,
        ));
    }

    /**
     * @Secure(roles="ROLE_RESPO")
     */
    public function newAction()
    {
        $event = new Event();

        $form = $this->createForm(new EventType, $event);

        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if( $form->isValid() )
            {
                $event->setSlug( $this->container->get('hflan_blog.slugify')->slugify($event->getName()) );
                $em = $this->getDoctrine()->getManager();
                $em->persist($event);
                $em->flush();

                $this->get('session')->setFlash('success', "tournament.message.success.new_event");
                return $this->redirect( $this->generateUrl('hflan_tournament_show_event', array('slug'=>$event->getSlug())) );
            }
            else
                $this->get('session')->setFlash('error', "message.error.form");
        }

        return $this->render('hflanTournamentBundle:Event:new.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @Secure(roles="ROLE_RESPO")
     */
    public function editAction(Event $event)
    {
        $form = $this->createForm(new EventType, $event);

        $request = $this->get('request');
        if( $request->getMethod() == 'POST' )
        {
            $form->bind($request);
            if( $form->isValid() )
            {
                $event->setSlug( $this->container->get('hflan_blog.slugify')->slugify($event->getName()) );
                $em = $this->getDoctrine()->getManager();
                $em->persist($event);
                $em->flush();

                $this->get('session')->setFlash('success', 'tournament.message.success.edit');
                return $this->redirect( $this->generateUrl('hflan_tournament_show_event', array('slug'=>$event->getSlug())) );
            }
            else
                $this->get('session')->setFlash('error', "message.error.form");
        }

        return $this->render('hflanTournamentBundle:Event:edit.html.twig', array(
            'form' => $form->createView(),
            'event' => $event,
        ));
    }

    /**
     * @Secure(roles="ROLE_RESPO")
     */
    public function deleteAction(Event $event)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($event);
        $em->flush();

        $this->get('session')->setFlash('success', 'tournament.message.success.delete');
        return $this->redirect( $this->generateUrl('hflan_tournament_index') );
    }

    /**
     * @Secure(roles="ROLE_RESPO")
     */
    public function showAction(Event $event)
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanTournamentBundle:Tournament');

        $tournaments = $repository->findByEvent($event);

        return $this->render('hflanTournamentBundle:Event:show.html.twig', array(
            'event' => $event,
            'tournaments'=>$tournaments,
        ));
    }

    public function menuAction()
    {
        $repository = $this->getDoctrine()
            ->getRepository('hflanTournamentBundle:Event');

        $nextEvent = $repository->getNextEvent();

        return $this->render('hflanTournamentBundle:Event:menu.html.twig', array(
            'nextEvent' => $nextEvent,
        ));
    }

    public function liveAction()
    {
        $repEvent = $this->getDoctrine()
            ->getRepository('hflanTournamentBundle:Event');

        $tournaments = $this->getDoctrine()
            ->getRepository('hflanTournamentBundle:Tournament')
            ->getTournamentWithEmbeddedPlayer($repEvent->getCurrentEvent());

        return $this->render('hflanTournamentBundle:Event:live.html.twig', array(
            'tournaments' => $tournaments,
        ));
    }
}

src/hflan/TournamentBundle/Resources/views/Event/edit.html.twig
{% extends "hflanTournamentBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}tournament.title.page.event.edit{% endtrans %}
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}tournament.title.page.event.edit{% endtrans %}</small>
{% endblock%}

{% block administration %}
<h2>{% trans %}tournament.title.aside.admin{% endtrans %}</h2>
<a href="{{ path('hflan_tournament_show_event', {slug: event.slug}) }}" class="btn"><i class="icon-remove icon-white"></i> {% trans %}tournament.action.cancel{% endtrans %}</a>
<hr>
{% endblock %}

{% block content %}

<form method="post" {{ form_enctype(form) }} class="form">
    {{ form_errors(form) }}
    <h3>{% trans %}tournament.title.form.global{% endtrans %}</h3>
    {{ form_row(form.name) }}
    {{ form_row(form.price) }}
    <h3>{% trans %}tournament.title.form.date{% endtrans %}</h3>
    {{ form_row(form.start_at) }}
    {{ form_row(form.end_at) }}
    {{ form_row(form.public) }}
    <h3>{% trans %}tournament.title.form.register{% endtrans %}</h3>
    {{ form_row(form.open_at) }}
    {{ form_row(form.close_at) }}
    {{ form_row(form.open) }}
    {{ form_rest(form) }}
    <div class="form-action">
        <button type="submit" class="btn"><i class="icon-ok icon-white"></i> {% trans %}tournament.action.save{% endtrans %}</button>
    </div>
</form>

{% endblock %}

src/hflan/TournamentBundle/Resources/views/Event/index.html.twig
{% extends "hflanTournamentBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}tournament.title.page.event.index{% endtrans %}
{% endblock %}

{% block administration %}
    {% if is_granted('ROLE_RESPO') %}
        <h2>{% trans %}tournament.title.aside.admin{% endtrans %}</h2>
        <a href="{{ path('hflan_tournament_new_event') }}" class="btn"><i class="icon-plus icon-white"></i> {% trans %}tournament.action.new{% endtrans %}</a>
        <hr>
    {% endif %}
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}tournament.title.page.event.index{% endtrans %}</small>
{% endblock%}

{% block content %}

<table class="table">
    <tr>
        <th>{% trans %}tournament.field.name{% endtrans %}</th>
        <th>{% trans %}tournament.field.price{% endtrans %}</th>
        <th>{% trans %}tournament.field.start_at{% endtrans %}</th>
        <th>{% trans %}tournament.title.form.register{% endtrans %}</th>
    </tr>
    {% for event in events %}
    <tr href="{{ path('hflan_tournament_show_event', {slug: event.slug}) }}">
        <td>{{ event.name }}</td>
        <td>{{ event.price }} €</td>

        {% if event.public %}
        <td>{{ event.startAt|toDate }}</td>
        {% else %}
        <td><i class="icon-eye-close"></i></td>
        {% endif %}

        {% if event.open %}
        <td>{{ event.openAt|toDate }}</td>
        {% else %}
        <td><i class="icon-eye-close"></i></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

{% endblock %}

src/hflan/TournamentBundle/Resources/views/Event/live.html.twig
{% extends "hflanTournamentBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}tournament.title.page.event.live{% endtrans %}
{% endblock %}

{% block sectionTitle %}
{% trans %}tournament.title.page.event.live{% endtrans %}
{% endblock%}

{% block administration %}
{% endblock %}

{% block tabs %}
    {% if tournaments is not empty %}
        <div class="tabs">
            <ul>
                {% for tournament in tournaments %}
                <li><a{{ loop.index == 1 ? ' class="active"':''}} href="#t{{ tournament.id }}">{{ tournament.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endblock %}

{% block content %}

{% if tournaments is not empty %}
    <div class="tab-content">
        {% for tournament in tournaments %}
        <div{{ loop.index == 1 ? ' class="active"':''}} id="t{{ tournament.id }}">
            {{ tournament.embeddedPlayer }}
        </div>
        {% endfor %}
    </div>
{% else %}
    {% trans %}tournament.message.error.no_stream{% endtrans %}
{% endif %}

{% endblock %}

src/hflan/TournamentBundle/Resources/views/Event/menu.html.twig
{% if nextEvent is not empty %}
<h2>{% trans %}tournament.title.aside.next_lan{% endtrans %}</h2>
<div id="defaultCountdown"></div>
{% if nextEvent.open %}
    {% if nextEvent.openAt > date('now', "Europe/Paris") %}
        <p>
            {% trans with {'%date%': nextEvent.openAt|toHuman} %}tournament.message.register.soon{% endtrans %}
        </p>
    {% else %}
        {% if nextEvent.closeAt > date('now', "Europe/Paris") %}
            <p>
                {% trans with {'%date%': nextEvent.closeAt|toHuman} %}tournament.message.register.open{% endtrans %}
            </p>
        {% else %}
            <p>
                {% trans %}tournament.message.register.close{% endtrans %}
            </p>
        {% endif %}
    {% endif %}
{% else %}
    <p>
    {% trans %}tournament.message.register.unknown{% endtrans %}
    </p>
{% endif %}

<hr>

<script type="text/javascript">
    var target = new Date({{ nextEvent.startAt|date('Y,m-1,j,G,i,s,u') }});
    $('#defaultCountdown').countdown({until: target});
</script>
{% endif %}

src/hflan/TournamentBundle/Resources/views/Event/new.html.twig
{% extends "hflanTournamentBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}tournament.title.page.event.new{% endtrans %}
{% endblock %}

{% block sectionTitle %}
{{ parent() }} <small>{% trans %}tournament.title.page.event.new{% endtrans %}</small>
{% endblock%}

{% block administration %}
<h2>{% trans %}tournament.title.aside.admin{% endtrans %}</h2>
<a href="{{ path('hflan_tournament_index') }}" class="btn"><i class="icon-remove icon-white"></i> {% trans %}tournament.action.cancel{% endtrans %}</a>
<hr>
{% endblock %}

{% block content %}

<form method="post" {{ form_enctype(form) }} class="form">
    {{ form_errors(form) }}
    <h3>{% trans %}tournament.title.form.global{% endtrans %}</h3>
    {{ form_row(form.name) }}
    {{ form_row(form.price) }}
    <h3>{% trans %}tournament.title.form.date{% endtrans %}</h3>
    {{ form_row(form.start_at) }}
    {{ form_row(form.end_at) }}
    {{ form_row(form.public) }}
    <h3>{% trans %}tournament.title.form.register{% endtrans %}</h3>
    {{ form_row(form.open_at) }}
    {{ form_row(form.close_at) }}
    {{ form_row(form.open) }}
    {{ form_rest(form) }}
    <div class="form-action">
        <button type="submit" class="btn"><i class="icon-ok icon-white"></i> {% trans %}tournament.action.save{% endtrans %}</button>
    </div>
</form>

{% endblock %}

src/hflan/TournamentBundle/Resources/views/Event/show.html.twig
{% extends "hflanTournamentBundle::layout.html.twig" %}

{% block title %}
{{ parent() }} - {% trans %}tournament.title.page.event.show{% endtrans %}
{% endblock %}

{% block administration %}
    {% if is_granted('ROLE_RESPO') %}
        <h2>{% trans %}tournament.title.aside.admin{% endtrans %}</h2>
        <p>
            <a href="{{ path('hflan_tournament_index') }}" class="btn">
                <i class="icon-backward icon-white"></i> {% trans %}tournament.action.back{% endtrans %}
            </a>
        </p>
        <p style="line-height: 30px;">
            <a href="{{ path('hflan_tournament_new_tournament', {slug: event.slug}) }}" class="btn">
                <i class="icon-plus icon-white"></i> {% trans %}tournament.action.add_tournament{% endtrans %}
            </a>
            <a href="{{ path('hflan_tournament_new_casu', {slug: event.slug}) }}" class="btn">
                <i class="icon-plus icon-white"></i> {% trans %}tournament.action.add_casu{% endtrans %}
            </a>
            <a href="{{ path('hflan_tournament_edit_event', {slug: event.slug})}}"  class="btn">
                <i class="icon-pencil icon-white"></i> {% trans %}tournament.action.edit{% endtrans %}
            </a>
            <a href="{{ path('hflan_tournament_delete_event', {slug: event.slug})}}"  class="btn">
                <i class="icon-remove icon-white"></i> {% trans %}tournament.action.delete{% endtrans %}
            </a>
        </p>
        <hr>
    {% endif %}
{% endblock %}

{% block sectionTitle %}
{{ event.name }} <small>{% trans %}tournament.title.page.event.show{% endtrans %}</small>
{% endblock%}

{% block content %}

{% if tournaments is empty %}
{% trans %}tournament.message.no_tournament{% endtrans %}
{% else %}
<table class="table">
    <tr>
        <th>{% trans %}tournament.field.name{% endtrans %}</th>
        <th>{% trans %}tournament.field.price{% endtrans %}</th>
        <th>{% trans %}tournament.field.prize_pool{% endtrans %}</th>
        <th>{% trans %}tournament.field.teams{% endtrans %}</th>
        <th>{% trans %}tournament.field.pending{% endtrans %}</th>
    </tr>
    {% for tournament in tournaments %}
        <tr href="{{ path('hflan_tournament_show_tournament', {slug: event.slug, id: tournament.id}) }}">
            <td>{{tournament.name}}</td>
            <td>{{tournament.price}} €</td>
            <td>{{tournament.prizePool}} €</td>
            <td>{{tournament.confirmedTeams}} / {{tournament.nbrTeams}}</td>
            <td>{{tournament.pendingTeams}}</td>
        </tr>
    {% endfor %}
</table>
{% endif %}

{% endblock %}